name: "Swift: Check"

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      ref:
        type: string
        description: "Reference to run checks with"
        default: ${{ github.ref }}
  pull_request:
    branches: [swift]

jobs:

  build:
    name: Build
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@0.0.13
    with:
      # macOS
      enable_macos_checks: false # (requires self-hosted runners)
      macos_build_command: "swift build"

      # iOS
      enable_ios_checks: false # (requires self-hosted runners)
      ios_build_command: "swift build"

      # Linux
      enable_linux_checks: true
      linux_build_command: "swift build"
      linux_swift_versions: '["6.2", "6.3"]'

      # Static Linux
      enable_linux_static_sdk_build: true
      linux_static_sdk_build_command: "swift build"
      linux_static_sdk_versions: '["6.2", "6.3"]'

      # Wasm
      enable_wasm_sdk_build: false
      wasm_sdk_build_command: "swift build"
      wasm_sdk_versions: '["6.3"]'

      # Embedded Wasm
      enable_embedded_wasm_sdk_build: false

      # Android
      enable_android_sdk_build: true
      android_sdk_build_command: "swift build"
      android_sdk_versions: '["6.3"]'

      # Windows
      enable_windows_checks: true
      enable_windows_docker: true
      windows_build_command: "Invoke-Program swift build"
      windows_swift_versions: '["6.2", "6.3"]'

      # FreeBSD
      enable_freebsd_checks: false
      freebsd_build_command: "swift build"
      freebsd_swift_versions: '[]'

  macos-build:
    name: macOS Build
    uses: ./.github/workflows/swift-check-macos.yml
    with:
      swift_versions: '["6.2", "6.3"]'

  ios-build:
    name: iOS Build
    uses: ./.github/workflows/swift-check-ios.yml
    with:
      swift_versions: '["6.2", "6.3"]'
